import type { LocaleSchema } from './en'

export const bg: LocaleSchema = {
  navbar: {
    brand:      'SkyWave',
    links:      ['Полети', 'Хотели', 'Пътешественици', 'Моите резервации'],
    activeLink: 'Полети',
    language:   'BG',
    signIn:     'Вход',
  },

  hero: {
    tagline: '✦ Твоето пътешествие започва тук',
    headline: { line1: 'Светът е', accent: 'по-близо', line2: 'отколкото мислиш' },
    subtitle: 'Умно търсене. Най-добрите сделки. Незабравими преживявания.',
  },

  search: {
    tabs:       { flights: 'Полети', hotels: 'Хотели', cars: 'Коли' },
    tripType:   'В една посока',
    roundTrip:  'Отиване и връщане',
    oneWay:     'В една посока',
    passengers: '1 Пътник',
    fields: {
      from:      { label: 'От',         value: 'София',       sub: 'SOF'       },
      to:        { label: 'До',         value: 'Навсякъде',   sub: 'Навсякъде' },
      departure: { label: 'Заминаване', value: '12 Юни, Чет'                   },
      return:    { label: 'Връщане',    value: 'Добави дата'                   },
    },
    filters:             ['Цена', 'Най-добро време', 'Директни полети', 'Багаж', 'Авиолинии'],
    flexibleDates:       'Гъвкави дати',
    from:                'от',
    noFlights:           'Няма намерени полети от това летище.',
    flightsFromAllDates: 'Полети от {city} — всички дати',
  },

  browse: {
    loading:            'Зареждане на летища…',
    originCountry:      'Страна на заминаване',
    destinationCountry: 'Страна на пристигане',
    flightsFrom:        'Полети от {city}',
    popular:            'Популярни',
    allCountries:       'Всички страни',
    pickAirport:        'Изберете летище',
    selectCountry:      'Изберете страна, за да видите летища',
    clear:              'Изчисти',
  },

  aiCopilot: {
    label:    'AI Умен Скорер Ко-Пилот',
    subtitle: 'Анализира въведеното — персонализирани резултати очаквайте',
    status:   'Оценява на живо',
    chat: {
      title:        'SkyWave AI',
      greeting:     'Здравей, {name}! Аз съм SkyWave AI. Попитай ме за полети, цени или резервации.',
      placeholder:  'Питай за полети, цени, дестинации…',
      send:         'Изпрати',
      errorMessage: 'Нещо се обърка. Моля, опитай отново.',
      emptyState:   'Няма съобщения. Кажи здравей!',
      suggestions:  [
        'Намери ми най-умните полети от София',
        'Покажи последните ми резервации',
        'Какви са най-евтините полети до Лондон?',
      ],
    },
  },

  stats: {
    countries: { value: '12', label: 'Посетени страни' },
    co2: { value: '350', unit: 'кг', label: 'CO₂ Отпечатък' },
    ecoRating: { value: '9.2', sub: 'Най-добра стойност', label: 'Еко оценка' },
  },

  guarantees: [
    { title: 'Гаранция за най-ниска цена', sub: 'Намираме най-евтините тарифи' },
    { title: 'Гъвкаво резервиране', sub: 'Промени или откажи лесно' },
    { title: 'Поддръжка 24/7', sub: 'Тук сме за теб по всяко време' },
    { title: 'Доверен от милиони', sub: 'Присъедини се към щастливи пътници' },
  ],

  socialFeed: { label: 'Социална активност на приятели' },

  destinations: {
    title: 'Популярни дестинации',
    subtitle: 'Харесвани места сред пътниците',
    from: 'от',
    currency: '€',
  },

  searchResults: {
    modifySearch:      'Промени търсенето',
    roundTrip:         'Отиване и връщане',
    oneWay:            'В една посока',
    allDates:          'Всички дати',
    fromPrice:         'от',
    returnLabel:       'Връщане',
    noReturnFlights:   'Няма намерени полети за връщане за {route}. Показват се само цени за отиване.',
    sort: { cheapest: 'Най-евтини', fastest: 'Най-бързи', best: 'Най-добри' },
    result:            'резултат',
    results:           'резултата',
    searching:         'Търсене на полети…',
    noFlightsFound:    'Няма намерени полети',
    tryDifferentDates: 'Опитайте различни дати или изберете „Всички дати"',
    direct:            'Директен',
    stop:              'спиране',
    stops:             'спирания',
    totalBothLegs:     'общо · двете посоки',
    outboundOnly:      'само отиване',
    perPerson:         'на човек',
    select:            'Избери',
    outbound:          'Отиване',
    return:            'Връщане',
  },

  booking: {
    noFlightSelected:    'Не е избран полет.',
    backToSearch:        'Обратно към търсенето',
    back:                'Назад',
    results:             'Резултати',
    stepOf:              'Стъпка {step} от 2',
    step1Label:          'Пътник и Допълнения',
    step2Label:          'Преглед и Плащане',
    tripSummary:         'Обобщение на пътуването',
    direct:              'Директен',
    stop:                'спиране',
    primaryPassenger:    'Основен Пътник',
    passengerSub:        'Въведете данните точно както са в паспорта / личната карта',
    givenNames:          'Имена',
    surnames:            'Фамилии',
    nationality:         'Гражданство',
    gender:              'Пол',
    dateOfBirth:         'Дата на раждане',
    selectCountry:       'Изберете страна',
    selectGender:        'Изберете',
    male:                'Мъж',
    female:              'Жена',
    other:               'Друго / предпочитам да не казвам',
    month:               'Месец',
    cabinBaggage:        'Ръчен Багаж',
    cabinBaggageSub:     'Изберете опция',
    personalItem:        'Личен предмет',
    personalItemSub:     'Трябва да се побира под предната седалка',
    personalItemDim:     '20 × 30 × 40 см',
    included:            'Включено',
    carryOnBundle:       'Пакет ръчен багаж',
    carryOnBundleSub:    'Личен предмет + ръчен багаж + приоритетно качване',
    carryOnBundleDim:    'до 20 кг',
    checkedBaggage:      'Чекиран Багаж',
    checkedBaggageSub:   'Голям багаж, съхраняван в трюма',
    noCheckedBaggage:    'Без чекиран багаж',
    bag23kg:             'Куфар 23 кг',
    bag23kgSub:          'Макс. 23 кг · твърд или мек куфар',
    travelInsurance:     'Пътническа Застраховка',
    insuranceSub:        'Защитете пътуването си',
    insProvider:         'от AXA Assistance',
    noInsurance:         'Без застраховка',
    noCoverage:          'Без покритие',
    insBasic:            'Пътническа Основна',
    insPlus:             'Пътническа Плюс',
    medical:             'Медицински разходи',
    cancellation:        'Анулиране на пътуване',
    assistance:          'Помощ',
    lostBaggage:         'Изгубен багаж',
    liability:           'Отговорност',
    free:                'Безплатно',
    continue:            'Продължи',
    passengerAndExtras:  'Пътник и допълнения',
    fullName:            'Пълно име',
    checkedBag:          'Чекиран багаж',
    insuranceNone:       'Няма',
    contactDetails:      'Данни за контакт',
    contactDetailsSub:   'Ще изпратим потвърждението на резервацията тук',
    email:               'Имейл',
    phone:               'Телефонен номер',
    payWithCard:         'Плати с карта',
    payWithCardSub:      'Приемат се всички основни карти',
    cardNumber:          'Номер на карта',
    expiry:              'Валидност (ММ/ГГ)',
    cvv:                 'CVV',
    nameOnCard:          'Имена на картата',
    securityNote:        'Плащането ви е защитено с 256-битово SSL криптиране. Чрез плащане се съгласявате с нашите Общи условия.',
    processing:          'Обработва се…',
    priceSummary:        'Обобщение на цената',
    adultRoundTrip:      '1× Възрастен (отиване и връщане)',
    adultOneWay:         '1× Възрастен (в една посока)',
    total:               'Общо',
    taxesNote:           'Включени всички данъци и такси',
    yourFlights:         'Вашите полети',
    bookingConfirmed:    'Резервацията е потвърдена!',
    bookingConfirmedSub: 'Вашето пътуване до {city} е готово.',
    bookingReference:    'Номер на резервация',
    passenger:           'Пътник',
    route:               'Маршрут',
    totalPaid:           'Платено общо',
    andBack:             'и обратно',
    viewBoardingPass:    'Виж бордна карта',
    signInTitle:         'Влезте за да видите резервациите си',
    signInSub:           'Историята на пътуванията ви е свързана с профила ви.',
    goToHomepage:        'Към началната страница',
    outbound:            'Отиване',
    return:              'Връщане',
  },

  myBookings: {
    home:             'Начало',
    nextFlight:       'Следващ полет',
    days:             'Дни',
    hrs:              'Часа',
    min:              'Мин',
    untilDeparture:   'до заминаване',
    departingNow:     'Заминава сега!',
    departure:        'Заминаване',
    flight:           'Полет',
    bookingRef:       'Рефер. номер',
    noUpcomingTrips:  'Няма предстоящи пътувания',
    summary:          'Обобщение',
    upcoming:         'Предстоящи',
    pastTrips:        'Минали пътувания',
    total:            'Общо',
    allTrips:         'Всички пътувания',
    sortFlight:       'Полет',
    sortBought:       'Купено',
    roundTrip:        'Отиване и връщане',
    oneWay:           'В една посока',
    showBoardingPass: 'Виж бордна карта',
    ref:              'Рефер.',
    flightConditions: 'Условия на полета',
    getToAirport:     'До летището',
    outbound:         'Отиване',
    return:           'Връщане',
    nonStop:          'Директен',
    noBookings:       'Все още няма резервации',
    noBookingsSub:    'Веднага щом резервирате полет, той ще се появи тук.',
    searchFlights:    'Търси полети',
    signIn:           'Влезте за да видите резервациите си',
    signInSub:        'Историята на пътуванията ви е свързана с профила ви.',
    goToHomepage:     'Към началната страница',
    loading:          'Зареждане на резервациите ви…',
  },

  boardingPass: {
    back:       'Назад',
    print:      'Печат',
    title:      'Вашата бордна карта',
    bookingRef: 'Номер на резервация:',
    paid:       'платено',
    noData:     'Не са намерени данни за бордна карта.',
    goHome:     'Към началото',
  },

  travelers: {
    searchPlaceholder:   'Търси пътешественици по име или имейл…',
    suggestedTravelers:  'Препоръчани пътешественици',
    noTravelersFound:    'Няма намерени пътешественици',
    noTravelersYet:      'Все още няма други пътешественици',
    follow:              'Последвай',
    following:           'Следван',
    close:               'Затвори',
    flight:              'полет',
    flights:             'полета',
    yourJourney:         'Вашето пътешествие',
    ofTheWorld:          'ОТ СВЕТА',
    keepExploring:       'Продължавайте да изследвате! Целият свят ви чака.',
    topCountries:        'Топ Страни',
    viewAll:             'Виж всички',
    flightsTotal:        'Общо полети',
    countriesVisited:    'Посетени',
    followersLabel:      'Хора',
    followingLabel:      'Пътешественици',
    travelersLabel:      'Пътешественици',
    followersTitle:      'Последователи',
    followingTitle:      'Следвани',
    editProfile:         'Редактирай профила',
    allVisitedCountries: 'Всички посетени страни',
    noCountriesVisited:  'Все още няма посетени страни.',
    people:              'Хора',
  },
}
